### ISSUE TITLE
Create image-tray that is accuate enough for tesseract/ pHash

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#13]

**Comment by Panzer23** [comment]
I was thinking.  Would it be easier to do this with hardware or software?  If we had the surface its on be like bright pink or something,  and if the card was always at the bottom of the slide, could you then detect the edge and crop from there?

**Comment by LittleRichard** [comment]
We discussed angling the tray a 5-10 degrees on both X and Y axes towards the back corner, so that gravity does the tight tolerance work for us.  Do you see a design constraint that would prevent this approach?  Would a well-designed cam have any issue pushing it out over an angled tray?  I have a feeling as long as the angles are right so gravity-feeding works consistently and the resolution is high enough, we'll be able to hard-code the crops.  

BUT, that's a really good idea.  If you can print it in a lurid color, it would give us the option to do it in software if we have to after testing gravity-feed.  That would involve openCV and is not ideal, but is definitely possible.

**Comment by Panzer23** [comment]
@LittleRichard Alright, no I do not see it as a major problem, as I was testing last night it seemed like a better idea just to have gravity do all the work and let the card slide off the end instead of pushing over the side edge.  If I didn't have to worry about the x co-ordinate at all it would mean all I would need is a servo to open and close a door at the end of the ramp.  I will continue along the path we discussed for now and let you know if I run into any trouble.

another option:
http://scikit-image.org/docs/stable/

**Comment by LittleRichard** [comment]
hmmmmmmmmmmmmmmmmmmm i didn't even think to just look for a basic edge detection thing in the standard image library, pillow.  Let me try running this in the next couple days and i'll let you know
http://stackoverflow.com/questions/9319767/image-outline-using-python-pil

When are you trying to print the part?  If we can do some software stuff to simplify the design that's always good, and my only objection was openCV so i can't see it taking a ton of time to get it working with Pillow if it has the capability

**Comment by LittleRichard** [comment]
Okay, i'll get you an answer in #14

**Comment by Panzer23** [comment]
Issue moved to #27 design is in place
