### ISSUE TITLE
Upgrade packages from Adafruit

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#69]
new libraries for the servo_hat and motor_hat now exist which are simpler to use and more consistent.  Need to update the firmware section to reflect that.

**Comment by Panzer23** [comment]
also #69. nice.

**Comment by LittleRichard** [comment]
can you post the steps you  used to install the new libraries for usage on the pi?  hopefully it's just a couple `pip install` commands

**Comment by Panzer23** [comment]
pip3 install adafruit-circuitpython-servokit
pip3 install adafruit-circuitpython-motorkit

for my own knowledge, pip3 forces python3 install, if it is the default language you just use pip?

**Comment by LittleRichard** [comment]
coooooool, that's all i should need to go and update the code that does the building. then we can talk  through how to update your RPi, but let's do it before you modify the firmware section so we can rip out the `sys.path` crap  and just import the libraries directly like civilized people

**Comment by Panzer23** [comment]
pinky up!

**Comment by LittleRichard** [comment]
for posterity:
https://github.com/adafruit/Adafruit_CircuitPython_ServoKit
https://github.com/adafruit/Adafruit_CircuitPython_MotorKit

**Comment by LittleRichard** [comment]
also `for my own knowledge, pip3 forces python3 install, if it is the default language you just use pip?`:

yes, and this is part of  what a virtualenv does  for you.  if you're  not in a virtual env `python` probably points to the binary for `python2` which points to some specific version binary like `python2.7`; the viritualenv overrides those links when you're in  an 'activated' virtualenv to point to whatever  you like.  the pip stuff works the same way; if it's a python3 virtual env the pip will point to pip3, but you can always invoke explicitly as well and use `python3 my_file.py` instead of `python my_file.py`

**Comment by Panzer23** [comment]
servo_kit has been updated and motor_kit has been depreciated by me.
